name: CI

on:
  push:
    branches: [ fox_9.0 ]
  pull_request:
    branches: [ fox_9.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out the repository in the required path.
      
    - name: Gets OrangeFox
      uses: srt32/git-actions@v0.0.3
      with:
        args: git clone --depth 1 https://gitlab.com/OrangeFox/Manifest.git --branch fox_9.0
        
    - name: Get our repository (Checkout@ won't cut it)
      uses: srt32/git-actions@v0.0.3
      with:
        args: git clone https://github.com/exadeci/ofox_device_realme_RMX1931.git --branch fox_9.0 device/realme/RMX1931
      
    - name: Update's OrangeFox from the remote.
      uses: srt32/git-actions@v0.0.3
      with:
        args: |
          cd Manifest
          git remote update
          git rebase origin/fox_9.0
    
    - name: Build target
      run: |
        cd Manifest
        lunch omni_RMX1931-eng
    
    - name: Build the recovery
      run: |
        cd Manifest
        mka recoveryimage
      env: 
        ALLOW_MISSING_DEPENDENCIES: true

    - name: Build the recovery
      if: success()
      run: |
        cd Manifest
        fastboot boot out/target/product/RMX1931/recovery.img
